function e(e,t,n,r,o,a,l){try{var i=e[a](l),s=i.value}catch(e){n(e);return}i.done?t(s):Promise.resolve(s).then(r,o)}const t=e=>e,n=(performance.now(),document.currentScript.outerHTML),r=document.body.innerHTML.replace(n,"");let o=0;function a(e){return e>=0?2*e:-2*e-1}const l=`사과
바나나
포도
딸기
오렌지
체리
복숭아
수박
파인애플
배
레몬
라즈베리
블루베리
키위
망고
참외
아보카도
석류
자몽
두리안
코코넛
라임
자두
무화과
감
살구
상추
양파
당근
감자
토마토
오이
시금치
호박
콩
옥수수
파프리카
브로콜리
고구마
아스파라거스
샐러리
양배추
고추
버섯
마늘
생강
비트
콜라비
아티초크
미역
김
호박
피망
죽순
무
고사리
갓
청경채
케일
취나물
치커리
미나리
더덕
토란
귤
대추
파파야
복분자
유자
부추
매실
호두
가지
노각`.split("\n"),i={s1:0,s2:0,setSeed(e){this.s1=e,this.s2=e},random(){return this.s1=1103515245*this.s1+12345&2147483647,this.s2^=this.s2<<13,this.s2^=this.s2>>17,this.s2^=this.s2<<5,t("random.random"),t(((this.s1^this.s2)+2147483648)/4294967295)}};function s(){let e;if(window.hwgInitialized)throw Error("Game was already initialized.");window.hwgInitialized=!0;let n=document.getElementById("stage"),r=[[3,2,1],[4,-1,0],[5,6,7]],[s,h,m]=[..."각".normalize("NFD")],f=12623-h.charCodeAt(0),p=Object.fromEntries(Object.entries({ㄱㄱ:"ㄲ",ㄱㅅ:"ㄳ",ㄴㅈ:"ㄵ",ㄴㅎ:"ㄶ",ㄷㄷ:"ㄸ",ㄹㄱ:"ㄺ",ㄹㅁ:"ㄻ",ㄹㅂ:"ㄼ",ㄹㅅ:"ㄽ",ㄹㅌ:"ㄾ",ㄹㅍ:"ㄿ",ㄹㅎ:"ㅀ",ㅂㅂ:"ㅃ",ㅂㅅ:"ㅄ",ㅅㅅ:"ㅆ",ㅈㅈ:"ㅉ",ㅏㅣ:"ㅐ",ㅑㅣ:"ㅒ",ㅓㅣ:"ㅔ",ㅕㅣ:"ㅖ",ㅗㅏ:"ㅘ",ㅗㅏㅣ:"ㅙ",ㅗㅣ:"ㅚ",ㅜㅓ:"ㅝ",ㅜㅓㅣ:"ㅞ",ㅜㅣ:"ㅟ",ㅡㅣ:"ㅢ"}).map(([e,t])=>[t,e])),g=-1,y=1;try{(e=function(e){if(null===e)return null;let[t,n]=e.split("|");if(C(t)!==1*n)throw Error("saved game state is corrupted");let r=JSON.parse(t);if(4!==r.GAME_VERSION)throw Error("The saved game state is from a different version of the game.");return r.completions?r.completions=r.completions.split(",").map(Number).reduce((e,t)=>(e.length&&4!==e.at(-1).length||e.push([]),e.at(-1).push(t),e),[]):r.completions=[],r}(d("gameState")))&&(y=e.stageNumber,n.textContent=y)}catch(e){console.error(e),delete localStorage.gameState}n.textContent=y;let w=function(e,t){var n;let r=a(e),o=a(t);return(n=.5*(r+o)*(r+o+1)+o)%2==0?n/2:-(n+1)/2}(y,o);i.setSeed(w);let v=[...l];function b(e){return[...e.normalize("NFC")].flatMap($)}let M=[];for(let e=0;e<16;e++)M.push(...v.splice(X(0,v.length-1),1));v.length=0;let E=document.getElementById("word-list"),S=document.getElementById("word-template");M.forEach(e=>{let t=S.content.cloneNode(!0).querySelector("li");t.textContent=e,t.dataset.word=e,E.appendChild(t)});let O=document.getElementById("jamo-board"),P=document.getElementById("jamo-template");O.addEventListener("selectstart",e=>{e.preventDefault()});let j=!1;O.addEventListener("contextmenu",e=>{j||e.preventDefault(),j=!1});let A="ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎㅏㅑㅓㅕㅗㅛㅜㅠㅡㅣ";function C(e){return[...e].map(e=>e.charCodeAt()).reduce((e,t)=>(e>>>1|(1&e)<<15)^t,0)}function L(){return{GAME_VERSION:4,width:12,height:12,completions:Array.from(O.querySelectorAll(".completion-bar")).filter(e=>e!==ea).map(e=>`${e.dataset.start},${e.dataset.end}`).join(),stageNumber:y}}function N(e=L()){let t=JSON.stringify(e);return`${t}|${C(t)}`}function $(e){let[t,n,r]=[...e.normalize("NFD")].concat(["","",""]).slice(0,3);return["ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ"[t.charCodeAt(0)-s.charCodeAt(0)],String.fromCharCode(n.charCodeAt(0)+f),r.length?"ㄱㄲㄳㄴㄵㄶㄷㄹㄺㄻㄼㄽㄾㄿㅀㅁㅂㅄㅅㅆㅇㅈㅊㅋㅌㅍㅎ"[r.charCodeAt(0)-m.charCodeAt(0)]:""].flatMap(e=>{var t;return[...null!==(t=p[e])&&void 0!==t?t:e]})}let x=()=>(t(x.name),t(A[X(0,A.length-1)])),I=M.flatMap(e=>[...e.normalize("NFC")].flatMap($)),k=()=>(t(k.name),t(I[X(0,I.length-1)]));function B(e,t){t.classList.add("no-transition"),e(),requestAnimationFrame(()=>{requestAnimationFrame(()=>{t.classList.remove("no-transition")})})}O.style.setProperty("--gap","0.75rem"),O.style.setProperty("--width",12),O.style.setProperty("--height",12),B(()=>{for(let e=0;e<144;e++){let e=P.content.cloneNode(!0).querySelector("i"),t=X(0,1)?x():k();e.dataset.jamo=t,O.appendChild(e)}},O);let R=Array.from({length:144},()=>null),q=(e,t,n,o)=>{if(n<0||n>7)throw RangeError("direction must be 0 to 7");for(let a=-1;a<=1;a++)for(let l=-1;l<=1;l++)if(r[a+1][l+1]===n)return[e+l*o,t+a*o]},z=O.querySelectorAll("#jamo-board>i");z.forEach((e,t)=>{e.dataset.index=t});let D=(e,t,n,r)=>{let o=b(e);if(o.length>12&&o.length>12)throw RangeError("word too long for board");for(let e=0;e<o.length;e++){let[a,l]=q(t,n,r,e);if(a<0||a>=12||l<0||l>=12)return!1;let i=R[12*l+a];if(i&&i!==o[e])return!1}for(let e=0;e<o.length;e++){let[a,l]=q(t,n,r,e),i=o[e],s=12*l+a;R[s]=i,z[s].dataset.jamo=i}return!0};function F(e,t){var n;let r=null!==(n=F.cache)&&void 0!==n?n:F.cache=new Map;if(r.has(e))return r.get(e);let o=t();return r.set(e,o),o}function T(e,t,n,r,o=null){let a=F(T,()=>document.getElementById("completion-bar-template")),l=null!=o?o:a.content.cloneNode(!0).querySelector(".completion-bar");l.dataset.start=`${e},${t}`,l.dataset.end=`${n},${r}`;let i=Math.min(e,n),s=Math.max(e,n),c=Math.min(t,r),d=Math.max(t,r),u=(s-i+1)*2+.75*(s-i),h=(d-c+1)*2+.75*(d-c);return l.style.setProperty("--top",`${2*c+.75*c}rem`),l.style.setProperty("--left",`${2*i+.75*i}rem`),l.style.setProperty("--width",`${u}rem`),l.style.setProperty("--height",`${h}rem`),l.style.setProperty("--thick","2.25rem"),l.style.setProperty("--hypot",`${Math.hypot(u,h)+.25}rem`),l.style.setProperty("--angle",`${180*Math.atan2(Math.sign(r-t)*h,Math.sign(n-e)*u)/Math.PI}deg`),l.style.setProperty("--hue",g+Math.floor(43758.5453*Math.sin(12.9898*e+78.233*t)%1*Y)*Math.floor(360/Y)),l}O.style.setProperty("--size","2rem");let V=0,G=document.getElementById("stage-clear-dialog"),H=G.querySelector("#next-stage"),J=G.querySelector("#cancel-next-stage");function U(e,t){V++,e.style.setProperty("--hue",t.style.getPropertyValue("--hue")),e.classList.add("found"),16===V&&G.showModal()}function X(e,n){return t(X.name),t([e,n]),t(Math.floor(i.random()*(n-e+1))+e)}H.addEventListener("click",()=>{var e,t;o=0;let n=L();u("gameState",N((e=function(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{},r=Object.keys(n);"function"==typeof Object.getOwnPropertySymbols&&(r=r.concat(Object.getOwnPropertySymbols(n).filter(function(e){return Object.getOwnPropertyDescriptor(n,e).enumerable}))),r.forEach(function(t){var r;r=n[t],t in e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r})}return e}({},n),t=t={completions:"",stageNumber:n.stageNumber+1},Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):(function(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);n.push.apply(n,r)}return n})(Object(t)).forEach(function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}),e))),c()},{passive:!0}),J.addEventListener("click",()=>{G.close()},{passive:!0});let Y=16;g=X(0,359);let _=Array.from({length:4},()=>16),W=64,K=()=>{let e=X(0,W-1),t=0;for(let n=0;n<4;n++)if(e<(t+=_[n]))return n};try{M.toSorted((e,t)=>b(t).length-b(e).length).forEach(e=>{let t,n,r;let a=0;for(;;){t=X(0,11),n=X(0,11);let l=((r=K())+6)%8;if(D(e,t,n,l)){_[r]--,W--,16-_[r]>16/3&&(W-=_[r],_[r]=0);break}if(a>256)throw o++,Error("Failed to populate a word to the board. Try increasing the size of the board or reducing the number of words. Retrying...");a++}})}catch(e){console.error(e),c();return}e&&e.completions.forEach(([e,t,n,r])=>{!function(e,t,n,r){let o=T(e,t,n,r),a=ec(es(e,t,n,r));U(E.querySelector(`li[data-word="${a}"]`),o),O.appendChild(o)}(e,t,n,r)});let Q=document.getElementById("dark-mode-toggle");Q.addEventListener("click",()=>{let e;let t=Q.dataset.mode,n=Q.dataset.modeOptions.split("|"),r=n[(n.indexOf(t)+1)%n.length];e=()=>{Q.dataset.mode=r,document.documentElement.dataset.mode=r},document.startViewTransition?document.startViewTransition(e):e(),localStorage.darkMode=r},{passive:!0});let Z=localStorage.darkMode;Z&&B(()=>{Q.dataset.mode=Z,document.documentElement.dataset.mode=Z},Q);let ee=new Proxy({value:!1},{set:(e,t,n)=>{if("value"===t&&"boolean"==typeof n)return Reflect.set(e,t,n)}}),et=[-1,-1],en=-1,er=[-1,-1];function eo(e,t){let[n,o]=e,[a,l]=t;if(!(n===a||o===l||Math.abs(n-a)===Math.abs(o-l)))return -1;let[i,s]=[a-n,l-o];return r[Math.sign(s)+1][Math.sign(i)+1]}let ea=null;function el(){if(!(-1!==et[0]&&-1!==et[1]))return;let e=null!==ea,[t,n]=et,[r,o]=-1===er[0]&&-1===er[1]?[t,n]:er;ea=T(t,n,r,o,ea),e||O.appendChild(ea)}function ei(e,t){let n=e<t?1:-1,r=[];for(let o=0;o<=Math.abs(t-e);o++)r.push(o*n+e);return r}function es(e,t,n,r){let o=ei(e,n),a=ei(t,r);return Array.from({length:Math.max(o.length,a.length)},(n,r)=>{var l,i;return[null!==(l=o[r])&&void 0!==l?l:e,null!==(i=a[r])&&void 0!==i?i:t]}).map(([e,t])=>z[12*t+e].dataset.jamo).join("")}function ec(e){return M.find(t=>{let[n,r]=F(t,()=>{let e=b(t);return[e.join(""),e.toReversed().join("")]});return n===e||r===e})}function ed(e,t,n){return e<t?t-e:e>n?e-n:0}function eu(e,t){let[n,r,o,a,l,i]=function(){let e=z[0],t=z[1],n=z[12],r=e.getBoundingClientRect(),o=t.getBoundingClientRect(),a=n.getBoundingClientRect(),l=o.left-r.left,i=a.top-r.top,s=r.left;return[s,r.top,l,i,o.left-r.right,a.top-r.bottom]}(),[s,c]=[e-(n-l/2),t-(r-i/2)],[d,u]=[Math.floor(s/o),Math.floor(c/a)];return[d,u]}function eh(e,t,n){return Math.min(n,Math.max(t,e))}O.addEventListener("pointerdown",e=>{if(e.target.matches("#jamo-board>i")){if(ee.value=!0,(et=eu(e.clientX,e.clientY))[0]<0||et[0]>=12||et[1]<0||et[1]>=12){et=[-1,-1];return}er=[-1,-1],en=-1,el()}},{passive:!0}),document.addEventListener("pointerup",e=>{j=2===e.button,ee.value=!1,et[0]===er[0]&&et[1]===er[1]?(null==ea||ea.remove(),ea=null):-1!==er[0]&&-1!==er[1]&&function(e){try{if(null===e)return;let[t,n]=e.dataset.start.split(",").map(Number),[r,o]=e.dataset.end.split(",").map(Number);if(t===r&&n===o){e.remove();return}let a=eo([t,n],[r,o]);if(-1===a){e.remove();return}let l=es(t,n,r,o),i=ec(l);if(i){let t=E.querySelector(`li[data-word="${i}"]`);t&&(t.classList.contains("found")?e.remove():U(t,e))}else e.remove()}finally{ea=null}}(ea)},{passive:!0}),document.addEventListener("pointermove",e=>{if(!ee.value)return;e.preventDefault();let t=eu(e.clientX,e.clientY);if(t[0]=eh(t[0],0,11),t[1]=eh(t[1],0,11),et[0]===t[0]&&et[1]===t[1])return;let n=eo(et,t);if(-1!==n?(er=t,en=n):-1!==er[0]&&-1!==er[1]&&(er=function(e,t,n){let[r,o]=e,[a,l]=t,[i,s]=[a-r,l-o],[c,d]=[a-r,l-o],[u,h]=[a-r,l-o];Math.abs(c)<Math.abs(d)?c=0:d=0,(u+h)%2&&(Math.abs(u)<Math.abs(h)?h-=Math.sign(h):u-=Math.sign(u));{let e=Math.abs(Math.abs(u)-Math.abs(h))/2;Math.abs(u)<Math.abs(h)?(u+=Math.sign(u)*e,h-=Math.sign(h)*e):(u-=Math.sign(u)*e,h+=Math.sign(h)*e)}let m=Math.abs(i-c)+Math.abs(s-d),f=Math.abs(i-u)+Math.abs(s-h);return m===f?n%2==0?[r+c,o+d]:[r+u,o+h]:m<f?[r+c,o+d]:[r+u,o+h]}(et,t,en)),!(-1!==er[0]&&-1!==er[1]))return;let[r,o]=er;if(r<0||r>=12||o<0||o>=12){let e=eo(et,[r,o]),t=ed(r,0,11),n=ed(o,0,11);[r,o]=q(r,o,e,-Math.max(t,n))}z[12*(er=[r,o])[1]+er[0]],el()}),e||u("gameState",N()),window.serializeGameState=N;let em=document.querySelector("main"),ef=()=>{let e=screen.availWidth,t=screen.availHeight;em.style.transform="scale(1)",em.style.margin="0";let{width:n,height:r}=em.getBoundingClientRect(),o=Math.min(1,e/n,t/r);em.style.transform=`scale(${o})`,em.style.margin=`${r*(o-1)/2}px ${n*(o-1)/2}px`};ef(),window.addEventListener("resize",ef,{passive:!0}),window.addEventListener("beforeunload",()=>{u("beforeunload",d("beforeunload",0)+1),d("gameState")&&u("gameState",N())},{passive:!0}),window.addEventListener("pagehide",()=>{u("pagehide",d("pagehide",0)+1)},{passive:!0}),performance.now()}function c(){[...document.body.children].filter(e=>e!==document.currentScript).forEach(e=>e.remove()),document.body.innerHTML=r,window.hwgInitialized=!1,s()}function d(e,t){let n=localStorage[e];return"string"==typeof n?JSON.parse(n):null!=t?t:null}function u(e,t){localStorage[e]=JSON.stringify(t)}window.average=function(e){return e.reduce((e,t)=>e+t,0)/e.length},window.median=function(e){let t=e.slice().sort((e,t)=>e-t),n=Math.floor(t.length/2);return t.length%2==0?(t[n-1]+t[n])/2:t[n]},window.getCurrentFunctionName=function(){return Error().stack.split("\n").slice(1)[1].match(/at (\w+)/)[1]},performance.now(),s(),function(){var t,n;let r=["ArrowUp","ArrowUp","ArrowDown","ArrowDown","ArrowLeft","ArrowRight","ArrowLeft","ArrowRight","b","a","Enter"],o=0,a=(t=function*(e){e.key===r[o]?++o===r.length&&(console.log("showing lunatic text"),window.removeEventListener("keydown",a)):o=0},n=function(){var n=this,r=arguments;return new Promise(function(o,a){var l=t.apply(n,r);function i(t){e(l,o,a,i,s,"next",t)}function s(t){e(l,o,a,i,s,"throw",t)}i(void 0)})},function(e){return n.apply(this,arguments)});window.addEventListener("keydown",a,{passive:!0})}(),document.getElementById("show-settings-panel").addEventListener("click",()=>{document.getElementById("settings-panel").showModal()});

//# sourceMappingURL=js.js.map